# -*- coding: utf-8 -*-
"""
@author: Sebi

File: dispZsurface.py
Date: 30.05.2017
Version. 1.2
"""


#from __future__ import print_function
from mpl_toolkits.mplot3d import axes3d
from matplotlib import cm
import matplotlib.pyplot as plt
import numpy as np
import os

def filterplanetable(planetable, ImageID=0, T=0, Z=0, CH=0):

    # TODO - Implement smart filtering without creating an itermediate table

    # filter planetable for specific imageID
    if ImageID > planetable['ImageID'].max():
        print('ImageID was invalid. Using ImageID = 0.')
        CH = 0
    pt = planetable[planetable['ImageID'] == ImageID]

    # filter planetable for specific timepoint
    if T > planetable['TheT'].max():
        print('Time Index was invalid. Using T = 0.')
        CH = 0
    pt = planetable[planetable['TheT'] == T]

    # filter resulting planetable pt for a specific z-plane
    if Z > planetable['TheZ'].max():
        print('Z-Plane Index was invalid. Using Z = 0.')
        zplane = 0
    pt = pt[pt['TheZ'] == Z]

    # filter planetable for specific channel
    if CH > planetable['TheC'].max():
        print('Channel Index was invalid. Using CH = 0.')
        CH = 0
    pt = planetable[planetable['TheC'] == CH]

    # return filtered planetable
    return pt


def scatterplot(planetable, ImageID=0, T=0, Z=0, CH=0, size=35,
                savefigure=False, figsavename='test.png', showsurface=True):
    """

    This function can be used to visualize al XYZ positions from an image file for
    the selcted channel and zplane as a scatterplot.

    :param planetable: XYZ planetable generated by bftools.get_planetable
    :param ImageID: zero-based ImageID indes (image series inside BioFormats)
    :param T: zero-based timepoint Index
    :param Z: zero-based zplane index
    :param CH: zero-based channel index
    :param size: maker size used to plot all YX positions
    :param savefigure: boolean
    :param filename: filename to save the figure as PNG
    :param showsurface: displays the surface as 3D plot
    :return: Plot and optional save figure as ...
    """

    ptf = filterplanetable(planetable, ImageID=0, T=0, Z=0, CH=0)

    # extract XYZ position for the selected channel
    xpos = ptf['XPos']
    ypos = ptf['YPos']
    zpos = ptf['ZPos']

    # normalize z-data by substracting the minimum value
    zpos_norm = zpos - zpos.min()

    #fig1 = plt.figure(figsize=(10, 6), dpi=100)
    fig1 = plt.figure()
    ax1 = fig1.add_subplot(111)
    ax1.grid(True)
    plt.axis('equal')

    # invert the Y-axis --> O,O = Top-Left
    ax1.invert_yaxis()

    ax1.autoscale(enable=True, axis='x', tight=True)
    ax1.autoscale(enable=True, axis='y', tight=True)

    # define the labels
    ax1.set_title('XYZ-Positions (norm) : ' + 'ImageID=' + str(ImageID) + ' T=' + str(T) + ' Z='+ str(Z) + ' CH=' + str(CH))
    ax1.set_xlabel('Stage X-Axis [micron]')
    ax1.set_ylabel('Stage Y-Axis [micron]')

    # plot data and label the colorbar
    sc1 = plt.scatter(xpos, ypos, marker='s', c=zpos_norm, s=size, cmap=cm.coolwarm)
    cb1 = plt.colorbar(sc1, fraction=0.046, shrink=0.8, pad=0.04)
    cb1.set_label('Z-Offset [micron]', labelpad=20)

    # optional save figure as PNG
    if savefigure:
        fig1.savefig(figsavename, dpi=100)
        print('Saved: ', figsavename)

    # optional 3D plot of surface
    if showsurface:

        fig2 = plt.figure(figsize=(10, 6), dpi=100)
        ax2 = fig2.add_subplot(111, projection='3d')

        # invert the Y-axis --> O,O = Top-Left
        ax2.invert_yaxis()

        ax1.autoscale(enable=True, axis='x', tight=True)
        ax1.autoscale(enable=True, axis='y', tight=True)
        ax1.autoscale(enable=True, axis='z', tight=True)

        # define the labels
        ax2.set_xlabel('Stage X-Axis [micron]')
        ax2.set_ylabel('Stage Y-Axis [micron]')
        ax2.set_zlabel('Z-Offset [micron]')

        # plot data and label the colorbar
        #sc2 = ax2.plot(xpos, ypos, zpos_norm, '.', markersize=10, cmap=plt.cm.coolwarm)
        sc2 = ax2.scatter(xpos, ypos, zpos_norm, marker='.', s=200, c=zpos_norm, cmap=plt.cm.coolwarm, depthshade=False)
        cb2 = plt.colorbar(sc2, shrink=0.8)
        cb2.set_label('Z-Offset [micron]', labelpad=20)

    if not showsurface:
        fig2 = None

    return fig1, fig2
